
package serverws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ws.Facture;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerServices", targetNamespace = "http://serverWS/")
@XmlSeeAlso({
    serverws.ObjectFactory.class,
    ws.ObjectFactory.class
})
public interface ServerServices {


    /**
     * 
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSumFacturesEntre1", targetNamespace = "http://serverWS/", className = "serverws.GetSumFacturesEntre1")
    @ResponseWrapper(localName = "getSumFacturesEntre1Response", targetNamespace = "http://serverWS/", className = "serverws.GetSumFacturesEntre1Response")
    @Action(input = "http://serverWS/ServerServices/getSumFacturesEntre1Request", output = "http://serverWS/ServerServices/getSumFacturesEntre1Response")
    public float getSumFacturesEntre1();

    /**
     * 
     * @return
     *     returns java.util.List<ws.Facture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFacturesEntre1", targetNamespace = "http://serverWS/", className = "serverws.GetFacturesEntre1")
    @ResponseWrapper(localName = "getFacturesEntre1Response", targetNamespace = "http://serverWS/", className = "serverws.GetFacturesEntre1Response")
    @Action(input = "http://serverWS/ServerServices/getFacturesEntre1Request", output = "http://serverWS/ServerServices/getFacturesEntre1Response")
    public List<Facture> getFacturesEntre1();

    /**
     * 
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSumFacturesEntre2", targetNamespace = "http://serverWS/", className = "serverws.GetSumFacturesEntre2")
    @ResponseWrapper(localName = "getSumFacturesEntre2Response", targetNamespace = "http://serverWS/", className = "serverws.GetSumFacturesEntre2Response")
    @Action(input = "http://serverWS/ServerServices/getSumFacturesEntre2Request", output = "http://serverWS/ServerServices/getSumFacturesEntre2Response")
    public float getSumFacturesEntre2();

    /**
     * 
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSumTotalFactures", targetNamespace = "http://serverWS/", className = "serverws.GetSumTotalFactures")
    @ResponseWrapper(localName = "getSumTotalFacturesResponse", targetNamespace = "http://serverWS/", className = "serverws.GetSumTotalFacturesResponse")
    @Action(input = "http://serverWS/ServerServices/getSumTotalFacturesRequest", output = "http://serverWS/ServerServices/getSumTotalFacturesResponse")
    public float getSumTotalFactures();

    /**
     * 
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSumFacturesEntre3", targetNamespace = "http://serverWS/", className = "serverws.GetSumFacturesEntre3")
    @ResponseWrapper(localName = "getSumFacturesEntre3Response", targetNamespace = "http://serverWS/", className = "serverws.GetSumFacturesEntre3Response")
    @Action(input = "http://serverWS/ServerServices/getSumFacturesEntre3Request", output = "http://serverWS/ServerServices/getSumFacturesEntre3Response")
    public float getSumFacturesEntre3();

    /**
     * 
     * @return
     *     returns java.util.List<ws.Facture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFacturesEntre2", targetNamespace = "http://serverWS/", className = "serverws.GetFacturesEntre2")
    @ResponseWrapper(localName = "getFacturesEntre2Response", targetNamespace = "http://serverWS/", className = "serverws.GetFacturesEntre2Response")
    @Action(input = "http://serverWS/ServerServices/getFacturesEntre2Request", output = "http://serverWS/ServerServices/getFacturesEntre2Response")
    public List<Facture> getFacturesEntre2();

    /**
     * 
     * @return
     *     returns java.util.List<ws.Facture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFacturesEntre3", targetNamespace = "http://serverWS/", className = "serverws.GetFacturesEntre3")
    @ResponseWrapper(localName = "getFacturesEntre3Response", targetNamespace = "http://serverWS/", className = "serverws.GetFacturesEntre3Response")
    @Action(input = "http://serverWS/ServerServices/getFacturesEntre3Request", output = "http://serverWS/ServerServices/getFacturesEntre3Response")
    public List<Facture> getFacturesEntre3();

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.Facture
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFactureEntre2", targetNamespace = "http://serverWS/", className = "serverws.GetFactureEntre2")
    @ResponseWrapper(localName = "getFactureEntre2Response", targetNamespace = "http://serverWS/", className = "serverws.GetFactureEntre2Response")
    @Action(input = "http://serverWS/ServerServices/getFactureEntre2Request", output = "http://serverWS/ServerServices/getFactureEntre2Response")
    public Facture getFactureEntre2(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.Facture
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFactureEntre3", targetNamespace = "http://serverWS/", className = "serverws.GetFactureEntre3")
    @ResponseWrapper(localName = "getFactureEntre3Response", targetNamespace = "http://serverWS/", className = "serverws.GetFactureEntre3Response")
    @Action(input = "http://serverWS/ServerServices/getFactureEntre3Request", output = "http://serverWS/ServerServices/getFactureEntre3Response")
    public Facture getFactureEntre3(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.Facture
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFactureEntre1", targetNamespace = "http://serverWS/", className = "serverws.GetFactureEntre1")
    @ResponseWrapper(localName = "getFactureEntre1Response", targetNamespace = "http://serverWS/", className = "serverws.GetFactureEntre1Response")
    @Action(input = "http://serverWS/ServerServices/getFactureEntre1Request", output = "http://serverWS/ServerServices/getFactureEntre1Response")
    public Facture getFactureEntre1(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
