
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_Entr2", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8585/SI_Entr2?wsdl")
public class SIEntr2
    extends Service
{

    private final static URL SIENTR2_WSDL_LOCATION;
    private final static WebServiceException SIENTR2_EXCEPTION;
    private final static QName SIENTR2_QNAME = new QName("http://ws/", "SI_Entr2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8585/SI_Entr2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIENTR2_WSDL_LOCATION = url;
        SIENTR2_EXCEPTION = e;
    }

    public SIEntr2() {
        super(__getWsdlLocation(), SIENTR2_QNAME);
    }

    public SIEntr2(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIENTR2_QNAME, features);
    }

    public SIEntr2(URL wsdlLocation) {
        super(wsdlLocation, SIENTR2_QNAME);
    }

    public SIEntr2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIENTR2_QNAME, features);
    }

    public SIEntr2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIEntr2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIEntre2Services
     */
    @WebEndpoint(name = "SIEntre2ServicesPort")
    public SIEntre2Services getSIEntre2ServicesPort() {
        return super.getPort(new QName("http://ws/", "SIEntre2ServicesPort"), SIEntre2Services.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIEntre2Services
     */
    @WebEndpoint(name = "SIEntre2ServicesPort")
    public SIEntre2Services getSIEntre2ServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "SIEntre2ServicesPort"), SIEntre2Services.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIENTR2_EXCEPTION!= null) {
            throw SIENTR2_EXCEPTION;
        }
        return SIENTR2_WSDL_LOCATION;
    }

}
