
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SIEntre2Services", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIEntre2Services {


    /**
     * 
     * @return
     *     returns java.util.List<ws.Facture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFactures", targetNamespace = "http://ws/", className = "ws.GetFactures")
    @ResponseWrapper(localName = "getFacturesResponse", targetNamespace = "http://ws/", className = "ws.GetFacturesResponse")
    @Action(input = "http://ws/SIEntre2Services/getFacturesRequest", output = "http://ws/SIEntre2Services/getFacturesResponse")
    public List<Facture> getFactures();

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.Facture
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFacture", targetNamespace = "http://ws/", className = "ws.GetFacture")
    @ResponseWrapper(localName = "getFactureResponse", targetNamespace = "http://ws/", className = "ws.GetFactureResponse")
    @Action(input = "http://ws/SIEntre2Services/getFactureRequest", output = "http://ws/SIEntre2Services/getFactureResponse")
    public Facture getFacture(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
